import type { Metadata } from 'next';
import Link from 'next/link';
import { getI18n } from '@/i18n/server';
import { getDataset } from '@/lib/data';

export const metadata: Metadata = {
  title: 'About the data',
  description:
    'Where Searchski data comes from, its licences, and what Searchski is and is not: a referral service, never a tour operator or merchant of record.',
};

/**
 * This page is a legal requirement, not decoration. See PLAN.md §9:
 *  * ODbL requires attribution and share-alike for OpenSkiMap/OSM-derived data.
 *  * Wikidata is CC0.
 *  * The referral-not-organiser statement is what keeps this project outside
 *    the EU Package Travel Directive's definition of a package organiser.
 * Do not remove or soften any of it.
 */

function H2({ children }: { children: React.ReactNode }) {
  return <h2 className="mt-8 text-base font-semibold text-fg">{children}</h2>;
}

function P({ children }: { children: React.ReactNode }) {
  return <p className="mt-2 text-sm leading-relaxed text-muted">{children}</p>;
}

function Ext({ href, children }: { href: string; children: React.ReactNode }) {
  return (
    <a href={href} target="_blank" rel="noopener noreferrer" className="text-accent">
      {children}
    </a>
  );
}

export default async function AboutPage() {
  const { t } = await getI18n();
  const data = await getDataset();

  return (
    <article className="mx-auto max-w-3xl pb-8">
      <h1 className="text-2xl font-semibold text-fg">{t('about.title')}</h1>
      <P>
        Searchski ranks ski resorts against what you actually asked for, and shows you the reason for
        every point it awarded. Nothing here is a review and nothing is generated by an AI: the
        ranking is a deterministic function of published, attributed data.
      </P>

      {/* ---------------------------------------------------------------
          THE LEGAL STATEMENT. Required, load-bearing, do not weaken.
         --------------------------------------------------------------- */}
      <div className="mt-6 rounded-xl border-2 border-accent/50 bg-accent-soft p-4">
        <h2 className="text-base font-semibold text-fg">
          Searchski is a referral service. It is not a tour operator.
        </h2>
        <p className="mt-2 text-sm leading-relaxed text-fg">
          Searchski does not sell flights, accommodation, lift passes, ski lessons, transfers, or
          packages of any kind. It never takes payment, never holds your money, and is{' '}
          <strong>never the merchant of record</strong>. Every booking link on this site sends you to
          an independent third-party company, and your contract for anything you book is with that
          company alone — not with Searchski.
        </p>
        <p className="mt-2 text-sm leading-relaxed text-fg">
          In particular, Searchski does not combine a flight with accommodation into a single sale.
          Under the EU Package Travel Directive (2015/2302) that combination would make the seller
          the &ldquo;organiser&rdquo; of a package: strictly liable for the performance of the whole
          trip and legally required to hold insolvency protection. Searchski presents separate links
          that you follow and book independently, which is not a package and does not create one.
        </p>
        <p className="mt-2 text-sm leading-relaxed text-fg">
          Some outbound links may be affiliate links, which pay Searchski a commission if you book.
          Those links are labelled <em>affiliate link</em> at the point of the click, and they never
          change the ranking — the scorer cannot see them.
        </p>
        <p className="mt-2 text-xs text-muted">This is a description of how the site works, not legal advice.</p>
      </div>

      <H2>Where the data comes from</H2>
      <div className="mt-3 overflow-x-auto">
        <table className="w-full min-w-[34rem] border-collapse text-sm">
          <thead>
            <tr className="border-b border-border text-start">
              <th scope="col" className="p-2 text-start text-xs font-medium text-muted">Source</th>
              <th scope="col" className="p-2 text-start text-xs font-medium text-muted">What it gives</th>
              <th scope="col" className="p-2 text-start text-xs font-medium text-muted">Licence</th>
            </tr>
          </thead>
          <tbody className="text-fg">
            <tr className="border-b border-border">
              <td className="p-2"><Ext href="https://openskimap.org/">OpenSkiMap</Ext></td>
              <td className="p-2 text-muted">Ski area geometry, pistes, lifts, elevations</td>
              <td className="p-2"><Ext href="https://opendatacommons.org/licenses/odbl/">ODbL</Ext></td>
            </tr>
            <tr className="border-b border-border">
              <td className="p-2"><Ext href="https://www.openstreetmap.org/copyright">OpenStreetMap</Ext></td>
              <td className="p-2 text-muted">Piste lighting, snowmaking, bars and restaurants near the base, map tiles</td>
              <td className="p-2"><Ext href="https://opendatacommons.org/licenses/odbl/">ODbL</Ext></td>
            </tr>
            <tr className="border-b border-border">
              <td className="p-2"><Ext href="https://www.wikidata.org/">Wikidata</Ext></td>
              <td className="p-2 text-muted">Identifiers, official websites, cross-references</td>
              <td className="p-2"><Ext href="https://creativecommons.org/publicdomain/zero/1.0/">CC0</Ext></td>
            </tr>
            <tr className="border-b border-border">
              <td className="p-2"><Ext href="https://open-meteo.com/">Open-Meteo</Ext></td>
              <td className="p-2 text-muted">Weather forecast, fetched live and never stored</td>
              <td className="p-2"><Ext href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</Ext></td>
            </tr>
            <tr>
              <td className="p-2">Hand curation</td>
              <td className="p-2 text-muted">Lift-pass prices, ski-school languages, pass-region membership</td>
              <td className="p-2 text-muted">Searchski, verification-gated</td>
            </tr>
          </tbody>
        </table>
      </div>

      <H2>Attribution</H2>
      <P>
        Ski area, piste and lift data is © OpenSkiMap and OpenStreetMap contributors, available under
        the Open Database Licence (ODbL). Map tiles are © OpenStreetMap contributors. Weather data is
        by Open-Meteo.com under CC BY 4.0. Wikidata content is CC0.
      </P>
      <P>
        Searchski merges these sources, re-derives its own metrics from them and presents them in its
        own structure. It does not mirror any single provider&apos;s catalogue, and it does not
        reproduce anyone&apos;s trail maps, photographs or editorial writing — those are copyrighted
        works. Where you want an operator&apos;s piste map, we link to it on their own site.
      </P>

      <H2>What &ldquo;not yet verified&rdquo; means</H2>
      <P>
        Some things cannot be derived from open data and have to be typed by a human, one resort at
        a time — lift-pass prices above all. Until a person has confirmed a row against a primary
        source it is marked <strong>not yet verified</strong>, shown as a claim rather than a fact,
        and it does not move a resort up or down the ranking.
      </P>
      <P>
        Prices are where this matters most. A lift pass found by automated search carries the page it
        came from and the date it was read, and many large resorts price dynamically — the figure
        shown is a floor, not a quote. Treat an unverified price as a lead to check before you budget
        a trip on it.
      </P>

      <H2>Things we deliberately do not claim to know</H2>
      <ul className="mt-2 list-disc space-y-1 ps-5 text-sm text-muted">
        <li>
          <strong className="text-fg">Crowding</strong> is modelled from lift types and standard
          hourly throughput divided by piste kilometres. It is a relative signal between resorts. It
          is not a measurement of queues and is never shown as one.
        </li>
        <li>
          <strong className="text-fg">Night skiing</strong> comes from OpenStreetMap&apos;s{' '}
          <code className="font-mono text-xs">lit</code> tag. Where that tag is absent we say{' '}
          <em>unknown</em>. We never turn missing data into &ldquo;no night skiing&rdquo;.
        </li>
        <li>
          <strong className="text-fg">Snowmaking</strong> is badly tagged in some countries. A zero
          usually means untagged, not absent, and the scorer treats it as missing rather than bad.
        </li>
        <li>
          <strong className="text-fg">Pass prices</strong> are collected by hand and go stale. Every
          price carries its season and its verification status.
        </li>
      </ul>

      <H2>Privacy</H2>
      <P>
        Searchski stores no accounts and no personal data. Your language choice, theme and comparison
        shortlist live in your own browser. Searches are processed and discarded. In line with GDPR
        we hold no named individuals in the dataset — no instructors, no staff, no review authors.
      </P>

      <H2>This deployment</H2>
      <P>
        Data source: <span className="font-mono">{data.meta.source}</span> ·{' '}
        {data.meta.areaCount.toLocaleString()} ski areas
        {data.meta.countries.length > 0 ? ` across ${data.meta.countries.join(', ')}` : ''}.
        {data.meta.isSample
          ? ' This deployment is serving the built-in sample dataset — the figures are placeholders, not researched data.'
          : ''}
      </P>

      <p className="mt-8">
        <Link href="/" className="text-sm text-accent no-underline">
          ← {t('nav.search')}
        </Link>
      </p>
    </article>
  );
}
